# Accessing data and mutating data

In [1]:
texts = [
    "The service at the restaurant was really impressive",
    "What is the status of my order number #1234?",
    "I have a proposal for a new feature in your app",
    "My package arrived late and the item was damaged",
    "Your team is doing an excellent job",
    "Could you help clarify the specifications of this product?",
    "I'm extremely dissatisfied with the customer service",
    "Have you thought about offering more plant-based options on your menu?",
    "I really appreciate the speedy response from your customer service team",
    "I enjoy using your application, great work"
]

Imagine if we have a requirement of getting only single value from the list. How can we do so?

We can use index. Index is the position of the element in our list. Like most other programming languages, Python starts counting from 0. So, the first element in the list has index 0, the second element has index 1, and so on.

In [2]:
print(texts[0])
print(texts[3])
print(texts[5])

The service at the restaurant was really impressive
My package arrived late and the item was damaged
Could you help clarify the specifications of this product?

Please take your time to compare the index, above result, and the list before moving on ðŸ˜„

# How to mutate?

One of the crucial things to understand about lists is that they are mutable, which means that we can change any of their elements after they have been created. We can do this by assigning new values to specific indexes.

In [3]:
names = [
    "John",
    "Jane",
    "Jack",
    "Jill",
    "James",
]

print(names[0])
names[0] = "Jonathan"
print(names[0])

John
Jonathan

# Mutating several elements at once in a list using for loop

We can also mutate several elements at once in a list using for loop. Let's say we want to change all the elements in the list to their multiplied value by 2, we can kinda doing it like below:

In [4]:
numbers = [
    1,
    2,
    3,
    4,
    5,
]

numbers[0] = numbers[0] * 2
numbers[1] = numbers[1] * 2
numbers[2] = numbers[2] * 2
numbers[3] = numbers[3] * 2
numbers[4] = numbers[4] * 2

print(numbers)

[2, 4, 6, 8, 10]

But of course it's time consuming to write the same line of code over and over again with only difference is in the index. So, we can use for loop to do so.

In [5]:
numbers = [
    1,
    2,
    3,
    4,
    5,
]

for index, number in enumerate(numbers):
    numbers[index] = number * 2

print(numbers)

[2, 4, 6, 8, 10]

Above code and the one before that is basically the same, but without the need to write the index over and over again.

Here we are using special function called `enumerate`, so we can create a foor loop that iterates over both the indexes and the elements in a list. Just to remind you, if we don't use enumerate, we can only code like this:

In [6]:
for number in numbers:
    print(number)

2
4
6
8
10

But because we want to mutate each element in the list, we need to know the index of each element. So, we can use enumerate to do so.

# Challenge!

# Challenge 1

Change the fourth name `Rahmat` to `Rahmat Adianto` in the list below.

In [8]:
names = [
    "Imran",
    "Jake",
    "Fadhil",
    "Rahmat",
    "Ricky"
]

# Add your code below
names[3] = "Rahmat Adianto"

When you are done with the above challenge, then:
1. Input your student_id and name in the box below
2. Run the code block by pressing the play button.

In [9]:
!pip install rggrader

from rggrader import submit

# @title #### Student Identity
student_id = "REA6UCWBO" # @param {type:"string"}
name = "Ida Bagus Teguh Teja Murti" # @param {type:"string"}

# Submit Method
assignment_id = "007_accessing_and_mutating_data_in_list"
question_id = "01_list_1"
submit(student_id, name, assignment_id, names[3], question_id)

Collecting rggrader
  Downloading rggrader-0.1.6-py3-none-any.whl.metadata (485 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from rggrader) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from rggrader) (2.2.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from rggrader) (11.0.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->rggrader) (1.16.0)
Downloading rggrader-0.1.6-py3-none-any.whl (2.5 kB)
Installing collected packages: rggrader
Successfully installed rggrader-0.1.6

'Assignment successfully submitted'

## Challenge 2

For the first challenge, we want to get the multiplied by 2 value of each element in the list. So when the list is [1, 2, 3, 4, 5], the result should be [2, 4, 6, 8, 10].

In [10]:
def multiplied_by_2(numbers):
    for index, number in enumerate(numbers):
        numbers[index] = number * 2
    return numbers

multiplied_by_2([1, 2, 3, 4, 5]) # Expected output: [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

When you are done with the above challenge, then:

1. Run the code block by pressing the play button.

In [11]:
# Submit Method
assignment_id = "007_accessing_and_mutating_data_in_list"
question_id = "02_list_2"

submit(student_id, name, assignment_id, str(multiplied_by_2([5, 7, 3, 4, 6])), question_id)

'Assignment successfully submitted'

## Challenge 3

Using `.upper()` method, change the array of string below to uppercase.

In [12]:
def change_to_uppercase(texts):
    for index, text in enumerate(texts):
        texts[index] = text.upper()
    return texts# Your answer here

change_to_uppercase(["hello", "world"]) # Expected output: ["HELLO", "WORLD"]

['HELLO', 'WORLD']

When you are done with the above challenge, then:

1. Run the code block by pressing the play button.

In [13]:
# Submit Method
assignment_id = "007_accessing_and_mutating_data_in_list"
question_id = "03_list_3"

submit(student_id, name, assignment_id, str(change_to_uppercase(["mastering", "ai"])), question_id)

'Assignment successfully submitted'

# Appending data

We can add new data to an existing list using the append() method. The append() method adds the data to the end of the list.

In [14]:
names = [
    "Peter",
    "John",
    "Mary",
    "George",
    "Paul",
]

print(names)
names.append("Jill")
print(names)

['Peter', 'John', 'Mary', 'George', 'Paul']
['Peter', 'John', 'Mary', 'George', 'Paul', 'Jill']

# Inserting data at specific index

If we want to insert data at a specific index rather than at the end of the list, we can use the insert() method.

In [15]:
names = [
    "Peter",
    "John",
    "Mary",
    "George",
    "Paul",
]

print(names)
names.insert(2, "Jill")
print(names)

['Peter', 'John', 'Mary', 'George', 'Paul']
['Peter', 'John', 'Jill', 'Mary', 'George', 'Paul']

As you can see above, `Jill` was added to the second index of the list and pushing the name `Mary` to be the third index.

# Popping data

We can remove the last data from a list using the pop() method. The pop() method returns the data that was removed.

In [16]:
names = [
    "Peter",
    "John",
    "Mary",
    "George",
    "Paul",
]

print(names)
names.pop()
print(names)

['Peter', 'John', 'Mary', 'George', 'Paul']
['Peter', 'John', 'Mary', 'George']

You can specify the index of the data you want to remove too like so:

In [17]:
names = [
    "Peter",
    "John",
    "Mary",
    "George",
    "Paul",
]

print(names)
names.pop(2)
print(names)

['Peter', 'John', 'Mary', 'George', 'Paul']
['Peter', 'John', 'George', 'Paul']

# Challenge!

# Challenge 1

Append new car named `Toyota` to the list of cars.

In [18]:
cars = ["BMW", "Audi", "Mercedes", "Volkswagen", "Porsche"]

# Add your code below!
cars.append('Toyota')
print(cars) # Expected output: ['BMW', 'Audi', 'Mercedes', 'Volkswagen', 'Porsche', 'Toyota']

['BMW', 'Audi', 'Mercedes', 'Volkswagen', 'Porsche', 'Toyota']

When you are done with the above challenge, then:
1. Input your student_id and name in the box below
2. Run the code block by pressing the play button.

In [19]:
!pip install rggrader

from rggrader import submit

# @title #### Student Identity
student_id = "REA6UCWBO" # @param {type:"string"}
name = "Ida Bagus Teguh Teja Murti " # @param {type:"string"}

# Submit Method
assignment_id = "008_more_on_list"
question_id = "01_more_list_1"
submit(student_id, name, assignment_id, cars[5], question_id)

Requirement already satisfied: rggrader in /usr/local/lib/python3.10/dist-packages (0.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from rggrader) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from rggrader) (2.2.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from rggrader) (11.0.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->rggrader) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->rggrader) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->rggrader) (1.16.0)

'Assignment successfully submitted'

## Challenge 2

Insert a new car named `Honda` between `Mercedes` and `Volkswagen`

In [21]:
cars = ["BMW", "Audi", "Mercedes", "Volkswagen", "Porsche"]

# Add your code below!
cars.insert(3, 'Honda')
print(cars) # Expected output: ['BMW', 'Audi', 'Mercedes', 'Honda', 'Volkswagen', 'Porsche']

['BMW', 'Audi', 'Mercedes', 'Honda', 'Volkswagen', 'Porsche']

When you are done with the above challenge, then:
1. Run the code block by pressing the play button.

In [22]:
# Submit Method
assignment_id = "008_more_on_list"
question_id = "02_more_list_2"

submit(student_id, name, assignment_id, cars[3], question_id)

'Assignment successfully submitted'

## Challenge 3

Remove "BMW" and "Porche" from the list of cars.

In [25]:
cars = ["BMW", "Audi", "Mercedes", "Volkswagen", "Porsche"]

# Add your code below!
cars.pop(0)
cars.pop(3)
print(cars) # Expected output: ['Audi', 'Mercedes', 'Volkswagen']

['Audi', 'Mercedes', 'Volkswagen']

When you are done with the above challenge, then:
1. Run the code block by pressing the play button.

In [26]:
# Submit Method
assignment_id = "008_more_on_list"
question_id = "03_more_list_3"

submit(student_id, name, assignment_id, cars[0], question_id)

'Assignment successfully submitted'

# Filtering data on list by creating a new list

We can filter data on a list by creating a new list. Let's say we want to filter out all employees who are not in the `Sales` department. We can do so by creating a new list and adding only the employees who are in the `Sales` department to the new list.

How so? Using combination of `for` loop and `if` statement of course!

In [27]:
all_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
odd_numbers = []

for number in all_numbers:
    if number % 2 == 1:
        odd_numbers.append(number)

print(odd_numbers)

[1, 3, 5, 7, 9]

# Challenge!

## Challenge 1

Create a new list of numbers that is greater than 5 from the list of numbers below.

In [28]:
all_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
greater_than_five = []

for number in all_numbers:
    if number > 5:
        greater_than_five.append(number)

print(greater_than_five) # Expected output: [6, 7, 8, 9]

[6, 7, 8, 9]

When you are done with the above challenge, then:
1. Run the code block by pressing the play button.

In [29]:
# Submit Method
assignment_id = "008_more_on_list"
question_id = "04_filter_1"

submit(student_id, name, assignment_id, str(greater_than_five), question_id)

'Assignment successfully submitted'

## Challenge 2

Get all names that are longer than 5 characters from the list of words below.

In [31]:
all_names = ['John', 'Ardian', 'Jill', 'Jennifer', 'Pahlevi', 'Ricky']
names_more_than_five_characters = []

# Add your code below!
for name in all_names:
    if len(name) > 5:
        names_more_than_five_characters.append(name)

print(names_more_than_five_characters) # Expected output: ['Ardian', 'Jennifer', 'Pahlevi']

['Ardian', 'Jennifer', 'Pahlevi']

When you are done with the above challenge, then:
1. Run the code block by pressing the play button.

In [32]:
# Submit Method
assignment_id = "008_more_on_list"
question_id = "05_filter_2"

submit(student_id, name, assignment_id, str(names_more_than_five_characters), question_id)

'Assignment successfully submitted'